In [1]:
import numpy as np

In [2]:
# shift + tab to view documentation
# alt + enter to run command
my_list = [1, 2, 3]

In [12]:
type(my_list)

list

In [4]:
myarray = np.array(my_list)

In [5]:
myarray

array([1, 2, 3])

In [6]:
type(myarray)

numpy.ndarray

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(shape=(5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(shape=(2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.random.seed(101)

In [11]:
arr = np.random.randint(0,100,10)

In [13]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [14]:
arr2 = np.random.randint(0,100, 10)

In [15]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [21]:
# find max and min of array and index
arr.max()

95

In [22]:
arr.argmax()

0

In [23]:
arr.min()

9

In [20]:
arr.argmin() 

7

In [24]:
arr.mean()

60.8

In [27]:
# reshape array
arr.reshape((2,5)) 


array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])